apiVersion: v1
kind: ConfigMap
metadata:
  name: kiit-lms-admin-frontend-config
  namespace: default
data:
  # Add any non-sensitive configuration here
  APP_ENV: "{{ENVIRONMENT}}"
  API_BASE_URL: "{{API_BASE_URL}}"

